### ISSUE TITLE
SSE connection is not restarted if server disconnects or restarts

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/Fint.Sse.Adapter.Skeleton#4]
https://github.com/FINTprosjektet/Fint.Sse.Adapter.Skeleton/blob/12495c572cc1f9d0b51721debfa6b2d2625e730b/Fint.Sse.Adapter/Services/HttpService.cs#L57-L61

```
2018-08-20 03:29:48 [Warning] [Fint.Services.HttpService] Could not POST { Action: "GET_ALL_PERSONALRESSURS", Client: "CACHE_SERVICE", CorrId: "f4cc0607-ee19-4717-98f1-d1c57cd2ed74", Message: null, OrgId: "pwf.no", Query: null, Source: "personal", Status: ADAPTER_RESPONSE, Time: 1534728487613, ResponseStatus: null, Problems: null, NumberOfDataElements: 10341 } to "https://beta.felleskomponent.no/administrasjon/personal/provider/response". Exception: HttpRequestException { Message: "Error while copying content to a stream.", Data: [], InnerException: IOException { Message: "Unable to read data from the transport connection: The connection was closed.", Data: [], InnerException: null, TargetSite: Void IOError(System.Exception, Boolean), StackTrace: "   at System.Net.ConnectStream.IOError(Exception exception, Boolean willThrow)
   at System.Net.ConnectStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()", HelpLink: null, Source: "System", HResult: -2146232800 }, TargetSite: Void MoveNext(), StackTrace: "   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
```

```
2018-08-20 03:31:06 [Verbose] [Fint.Services.HttpService] Task was canceled before post was done "https://beta.felleskomponent.no/administrasjon/personal/provider/status". Exception: TaskCanceledException { Task: Task`1 { Result: "The property accessor threw an exception: AggregateException", Id: 1130193, Exception: null, Status: Canceled, IsCanceled: True, IsCompleted: True, CreationOptions: None, AsyncState: null, IsFaulted: False }, CancellationToken: CancellationToken { IsCancellationRequested: False, CanBeCanceled: False, WaitHandle: ManualResetEvent { Handle: IntPtr {  }, SafeWaitHandle: SafeWaitHandle { IsInvalid: False, IsClosed: False } } }, Message: "A task was canceled.", Data: [], InnerException: null, TargetSite: Void ThrowForNonSuccess(System.Threading.Tasks.Task), StackTrace: "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EvryFint.Services.HttpService.<Post>d__4.MoveNext() in d:\dev\workspaces\integrasjoner\fint\main\src\Evry.Fint.UbwService\Services\HttpService.cs:line 96", HelpLink: null, Source: "mscorlib", HResult: -2146233029 } ---- { Action: "GET_ALL_VARIABELLONN", Client: "CACHE_SERVICE", CorrId: "f5460a04-02cc-49ec-9d96-7b3174959138", Message: null, OrgId: "pwf.no", Query: null, Source: "personal", Status: ADAPTER_ACCEPTED, Time: 1534728497612 }  {ThreadId: 49}
```

**Comment by jarlehansen** [comment]
I am not that happy with the c# implementation of the sse client, wish there was a better open source alternative.
Will see what we can do with this...

**Comment by jarlehansen** [comment]
I will look into this: https://docs.servicestack.net/csharp-server-events-client
